// Fungi Source — the working collection. Every book is a real, verified
// public-domain scan on the Internet Archive (full downloads available; links
// checked) with a self-hosted cover, plus a wall of the finest public-domain
// plates from Wikimedia Commons. This is the seed of the open database that gets
// translated, catalogued and ported into Source Library.

export type FungiBook = {
  title: string;
  author: string;
  year: string;
  language: string;
  pages: number; // scanned leaf count (Internet Archive imagecount)
  illustrations: number; // documented plate / figure count (0 = essentially text-only)
  importance: number; // 0–100 — historical significance blended with popularity
  note: string;
  rights: "Public domain";
  source: string;
  url: string; // full book — Internet Archive
  image: string; // self-hosted cover
  inSourceLibrary?: boolean; // already catalogued in the Source Library mycology collection
};

const ia = (id: string) => `https://archive.org/details/${id}`;
const cover = (id: string) => `/fungi-source/covers/${id}.jpg`;

export const FUNGI_BOOKS: FungiBook[] = [
  { title: "Nova plantarum genera", author: "Pier Antonio Micheli", year: "1729", language: "Latin", note: "The pre-Linnaean landmark that founded scientific mycology.", pages: 478, illustrations: 108, importance: 95, rights: "Public domain", source: "Internet Archive", url: ia("novaplantarvmgen00mich"), image: cover("novaplantarvmgen00mich"), inSourceLibrary: true },
  { title: "Fungorum qui in Bavaria… icones", author: "Jacob Christian Schäffer", year: "1762–74", language: "Latin", note: "Among the earliest fungal works with hand-coloured plates.", pages: 454, illustrations: 330, importance: 84, rights: "Public domain", source: "Internet Archive", url: ia("fungorumquiinbav34schf"), image: cover("fungorumquiinbav34schf"), inSourceLibrary: true },
  { title: "Histoire des champignons de la France", author: "Pierre Bulliard", year: "1791–1812", language: "French", note: "One of the earliest colour-printed botanical works — a foundational illustrated treatise.", pages: 362, illustrations: 600, importance: 88, rights: "Public domain", source: "Internet Archive", url: ia("b30454694"), image: cover("b30454694"), inSourceLibrary: true },
  { title: "Coloured Figures of English Fungi", author: "James Sowerby", year: "1797–1809", language: "English", note: "The most celebrated English illustrated mycology — 440 hand-coloured plates.", pages: 1124, illustrations: 440, importance: 86, rights: "Public domain", source: "Internet Archive", url: ia("colouredfigureso00sowe"), image: cover("colouredfigureso00sowe"), inSourceLibrary: true },
  { title: "Synopsis Methodica Fungorum", author: "Christiaan Hendrik Persoon", year: "1801", language: "Latin", note: "A nomenclatural bedrock for rusts, smuts and gasteromycetes.", pages: 760, illustrations: 5, importance: 97, rights: "Public domain", source: "Internet Archive", url: ia("synopsismethodi00pers"), image: cover("synopsismethodi00pers"), inSourceLibrary: true },
  { title: "Conspectus Fungorum in Lusatiae superioris", author: "Albertini & Schweinitz", year: "1805", language: "Latin", note: "An early systematic landmark of central-European fungi.", pages: 442, illustrations: 12, importance: 60, rights: "Public domain", source: "Internet Archive", url: ia("conspectusfungor00albe"), image: cover("conspectusfungor00albe") },
  { title: "Systema Mycologicum", author: "Elias Magnus Fries", year: "1821–32", language: "Latin", note: "The great nomenclatural starting point of fungal taxonomy.", pages: 592, illustrations: 0, importance: 98, rights: "Public domain", source: "Internet Archive", url: ia("systemamycologic01frie"), image: cover("systemamycologic01frie"), inSourceLibrary: true },
  { title: "Naturgetreue Abbildungen… der Schwämme", author: "J. V. von Krombholz", year: "1831–46", language: "German", note: "A lavish guide to edible, harmful and suspect mushrooms — 76 colour plates.", pages: 77, illustrations: 76, importance: 84, rights: "Public domain", source: "Internet Archive", url: ia("mobot31753002807052"), image: cover("mobot31753002807052") },
  { title: "Funghi d'Italia", author: "Domenico Viviani", year: "1834", language: "Italian", note: "Sixty colour plates of the fungi of Italy.", pages: 172, illustrations: 60, importance: 62, rights: "Public domain", source: "Internet Archive", url: ia("TO01052542"), image: cover("TO01052542") },
  { title: "Descrizione dei funghi mangerecci… dell'Italia", author: "Carlo Vittadini", year: "1835", language: "Italian", note: "Forty-four colour plates of the common edible fungi of Italy.", pages: 474, illustrations: 44, importance: 70, rights: "Public domain", source: "Internet Archive", url: ia("descrizionedeifu00vitt"), image: cover("descrizionedeifu00vitt") },
  { title: "A Treatise on the Esculent Funguses of England", author: "Charles David Badham", year: "1847", language: "English", note: "The mycophagy classic, illustrated with Hussey's plates.", pages: 242, illustrations: 20, importance: 68, rights: "Public domain", source: "Internet Archive", url: ia("treatiseonescule00badh_0"), image: cover("treatiseonescule00badh_0") },
  { title: "Illustrations of British Mycology", author: "Anna Maria Hussey", year: "1847–55", language: "English", note: "140 hand-coloured lithographs by one of Britain's first female mycologists.", pages: 402, illustrations: 140, importance: 74, rights: "Public domain", source: "Internet Archive", url: ia("illustrationsofbser01huss"), image: cover("illustrationsofbser01huss") },
  { title: "Sveriges ätliga och giftiga svampar", author: "Elias Magnus Fries", year: "1862–69", language: "Swedish", note: "Ninety-three colour plates of Sweden's edible and poisonous fungi.", pages: 280, illustrations: 94, importance: 82, rights: "Public domain", source: "Internet Archive", url: ia("sverigesatligaoc1861frie"), image: cover("sverigesatligaoc1861frie") },
  { title: "Rambles in Search of Flowerless Plants", author: "Margaret Plues", year: "1864", language: "English", note: "Field narrative blended with hand-coloured lithographs.", pages: 380, illustrations: 20, importance: 52, rights: "Public domain", source: "Internet Archive", url: ia("ramblesinsearcho00plue"), image: cover("ramblesinsearcho00plue") },
  { title: "Rust, Smut, Mildew & Mould", author: "Mordecai Cubitt Cooke", year: "1865", language: "English", note: "The go-to early introduction to the microscopic fungi.", pages: 316, illustrations: 16, importance: 72, rights: "Public domain", source: "Internet Archive", url: ia("rustsmutmildewmo00cook"), image: cover("rustsmutmildewmo00cook") },
  { title: "Morphologie und Physiologie der Pilze", author: "Anton de Bary", year: "1866", language: "German", note: "Foundational science — the morphology and physiology of the fungi.", pages: 208, illustrations: 102, importance: 86, rights: "Public domain", source: "Internet Archive", url: ia("beitragezurmorph45bary"), image: cover("beitragezurmorph45bary") },
  { title: "Handbook of British Fungi", author: "Mordecai Cubitt Cooke", year: "1871", language: "English", note: "The systematic handbook of British fungi.", pages: 524, illustrations: 408, importance: 74, rights: "Public domain", source: "Internet Archive", url: ia("handbookofbritis01cook"), image: cover("handbookofbritis01cook") },
  { title: "Les Hyménomycètes", author: "Claude-Casimir Gillet", year: "1874–98", language: "French", note: "A descriptive flora of the hymenomycetes of France.", pages: 216, illustrations: 714, importance: 78, rights: "Public domain", source: "Internet Archive", url: ia("leschampignonsfu01gill"), image: cover("leschampignonsfu01gill") },
  { title: "Fungi: Their Nature and Uses", author: "Mordecai Cubitt Cooke", year: "1875", language: "English", note: "The readable Victorian overview of what fungi are and do.", pages: 338, illustrations: 109, importance: 66, rights: "Public domain", source: "Internet Archive", url: ia("fungitheirnature00cookrich"), image: cover("fungitheirnature00cookrich") },
  { title: "Edible and Poisonous Fungi", author: "Worthington G. Smith", year: "1876", language: "English", note: "Blunt, charming and practical — “I have constantly eaten every species figured…”.", pages: 78, illustrations: 60, importance: 50, rights: "Public domain", source: "Internet Archive", url: ia("b28057971"), image: cover("b28057971") },
  { title: "Illustrations of British Fungi", author: "Mordecai Cubitt Cooke", year: "1881–91", language: "English", note: "A monumental 8-volume atlas of 1,100+ colour plates.", pages: 610, illustrations: 1198, importance: 85, rights: "Public domain", source: "Internet Archive", url: ia("illustrationsofb02cook"), image: cover("illustrationsofb02cook"), inSourceLibrary: true },
  { title: "Sylloge Fungorum", author: "Pier Andrea Saccardo", year: "1882–", language: "Latin", note: "The vast catalogue gathering every described fungus into one work.", pages: 1168, illustrations: 0, importance: 94, rights: "Public domain", source: "Internet Archive", url: ia("syllogefungorumo05sacc"), image: cover("syllogefungorumo05sacc"), inSourceLibrary: true },
  { title: "Vergleichende Morphologie und Biologie der Pilze", author: "Anton de Bary", year: "1884", language: "German", note: "Comparative morphology and biology of the fungi — a science classic.", pages: 590, illustrations: 198, importance: 88, rights: "Public domain", source: "Internet Archive", url: ia("vergleichendemor00bary"), image: cover("vergleichendemor00bary") },
  { title: "Our Edible Toadstools and Mushrooms", author: "W. Hamilton Gibson", year: "1895", language: "English", note: "Exquisite author-drawn plates of thirty edible species.", pages: 424, illustrations: 37, importance: 72, rights: "Public domain", source: "Internet Archive", url: ia("cu31924002064842"), image: cover("cu31924002064842") },
  { title: "Student's Hand-book of the Mushrooms of America", author: "Thomas Taylor", year: "1897", language: "English", note: "An early American identification handbook.", pages: 206, illustrations: 27, importance: 52, rights: "Public domain", source: "Internet Archive", url: ia("studentshandbook00tayl"), image: cover("studentshandbook00tayl") },
  { title: "I funghi mangerecci e velenosi", author: "Giacomo Bresadola", year: "1899", language: "Italian", note: "The edible and poisonous fungi of central Europe — ~120 colour plates.", pages: 392, illustrations: 113, importance: 78, rights: "Public domain", source: "Internet Archive", url: ia("ifunghimangerecce00bres"), image: cover("ifunghimangerecce00bres") },
  { title: "Studies of American Fungi", author: "George F. Atkinson", year: "1900", language: "English", note: "An early, serious use of photography in mycology.", pages: 476, illustrations: 80, importance: 72, rights: "Public domain", source: "Internet Archive", url: ia("studiesofamerica00atki"), image: cover("studiesofamerica00atki") },
  { title: "One Thousand American Fungi", author: "Charles McIlvaine", year: "1900", language: "English", note: "The 700-page survey by the fearless taster “Old Ironguts”.", pages: 916, illustrations: 211, importance: 76, rights: "Public domain", source: "Internet Archive", url: ia("toadstoolsmushro00mcil"), image: cover("toadstoolsmushro00mcil") },
  { title: "Among the Mushrooms: A Guide for Beginners", author: "Dallas & Burgin", year: "1900", language: "English", note: "An approachable beginner's guide to common fungi.", pages: 212, illustrations: 12, importance: 48, rights: "Public domain", source: "Internet Archive", url: ia("amongmushroomsgu00dall"), image: cover("amongmushroomsgu00dall") },
  { title: "Führer für Pilzfreunde", author: "Edmund Michael", year: "c. 1901", language: "German", note: "The enormously popular German field guide, with colour plates.", pages: 164, illustrations: 56, importance: 70, rights: "Public domain", source: "Internet Archive", url: ia("fhrerfrpilzfreun00mich"), image: cover("fhrerfrpilzfreun00mich") },
  { title: "The Mushroom Book", author: "Nina L. Marshall", year: "1901", language: "English", note: "A beautifully produced American popular guide.", pages: 280, illustrations: 48, importance: 70, rights: "Public domain", source: "Internet Archive", url: ia("mushroombookpopu00marsrich"), image: cover("mushroombookpopu00marsrich") },
  { title: "Icones mycologicae", author: "Émile Boudier", year: "1905–10", language: "French", note: "Some six hundred exquisite colour plates of European fungi.", pages: 486, illustrations: 600, importance: 88, rights: "Public domain", source: "Internet Archive", url: ia("iconesmycologic02boud"), image: cover("iconesmycologic02boud") },
  { title: "A Text-book of Fungi", author: "George Massee", year: "1906", language: "English", note: "A systematic text-book — morphology, physiology and classification.", pages: 456, illustrations: 120, importance: 64, rights: "Public domain", source: "Internet Archive", url: ia("textbookoffungii00massuoft"), image: cover("textbookoffungii00massuoft") },
  { title: "The Mushroom, Edible and Otherwise", author: "Miron Elisha Hard", year: "1908", language: "English", note: "A thorough, photo-illustrated American manual.", pages: 638, illustrations: 504, importance: 66, rights: "Public domain", source: "Internet Archive", url: ia("mushroomedibleot00harduoft"), image: cover("mushroomedibleot00harduoft") },
  { title: "Rariorum plantarum historia", author: "Carolus Clusius", year: "1601", language: "Latin", note: "Contains Clusius's pioneering Fungorum historia — among the very first fungal treatises.", pages: 749, illustrations: 33, importance: 90, rights: "Public domain", source: "Internet Archive", url: ia("caroliclusiatre00clus"), image: cover("caroliclusiatre00clus"), inSourceLibrary: true },
  { title: "Theatrum Fungorum", author: "Franciscus van Sterbeeck", year: "1675", language: "Dutch", note: "One of the earliest printed mushroom books â the Flemish “theatre of fungi”.", pages: 491, illustrations: 36, importance: 78, rights: "Public domain", source: "Internet Archive", url: ia("mobot31753000540531"), image: cover("mobot31753000540531"), inSourceLibrary: true },
  { title: "Fungorum agri Ariminensis historia", author: "Giovanni Antonio Battarra", year: "1755", language: "Latin", note: "A finely engraved regional flora of the Rimini fungi — 40 copperplates.", pages: 176, illustrations: 40, importance: 74, rights: "Public domain", source: "Internet Archive", url: ia("fungorumagriari00batt"), image: cover("fungorumagriari00batt"), inSourceLibrary: true },
  { title: "Scottish Cryptogamic Flora", author: "Robert Kaye Greville", year: "1823–28", language: "English", note: "360 hand-coloured plates of Scottish fungi and cryptogams.", pages: 269, illustrations: 360, importance: 76, rights: "Public domain", source: "Internet Archive", url: ia("scottishcryptog05grevgoog"), image: cover("scottishcryptog05grevgoog") },
  { title: "Figures des champignons", author: "J. B. L. Letellier", year: "1839", language: "French", note: "A companion plate volume extending Bulliard's iconography.", pages: 234, illustrations: 108, importance: 58, rights: "Public domain", source: "Internet Archive", url: ia("figuresdeschampi00lete"), image: cover("figuresdeschampi00lete") },
  { title: "Histoire des champignons comestibles et vénéneux", author: "Joseph Roques", year: "1841", language: "French", note: "A classic illustrated French treatise on edible vs poisonous fungi.", pages: 496, illustrations: 24, importance: 60, rights: "Public domain", source: "Internet Archive", url: ia("b24923527_0001"), image: cover("b24923527_0001") },
  { title: "Iconographie des champignons de Paulet", author: "J. H. Léveillé", year: "1855", language: "French", note: "217 engraved and coloured plates — a landmark mushroom atlas.", pages: 600, illustrations: 217, importance: 78, rights: "Public domain", source: "Internet Archive", url: ia("iconographiedesc00lv"), image: cover("iconographiedesc00lv"), inSourceLibrary: true },
  { title: "Outlines of British Fungology", author: "Miles Joseph Berkeley", year: "1860", language: "English", note: "The first comprehensive systematic handbook of British fungi.", pages: 588, illustrations: 24, importance: 74, rights: "Public domain", source: "Internet Archive", url: ia("outlinesofbritis00berk"), image: cover("outlinesofbritis00berk"), inSourceLibrary: true },
  { title: "Selecta Fungorum Carpologia", author: "L.-R. & C. Tulasne", year: "1861", language: "Latin", note: "The Tulasne brothers' landmark carpology of microfungi, finely engraved.", pages: 376, illustrations: 61, importance: 86, rights: "Public domain", source: "Internet Archive", url: ia("mobot31753000797784"), image: cover("mobot31753000797784"), inSourceLibrary: true },
  { title: "Illustrations of the Fungi of Our Fields and Woods", author: "Sarah Price", year: "1864", language: "English", note: "A hand-illustrated British fungi folio by a 19th-c woman naturalist.", pages: 60, illustrations: 20, importance: 48, rights: "Public domain", source: "Internet Archive", url: ia("illustrationsfu00pric"), image: cover("illustrationsfu00pric") },
  { title: "Funghi siciliani", author: "Giuseppe Inzenga", year: "1865", language: "Italian", note: "A classic regional study of the edible and poisonous fungi of Sicily.", pages: 228, illustrations: 8, importance: 45, rights: "Public domain", source: "Internet Archive", url: ia("funghisiciliani00inze"), image: cover("funghisiciliani00inze") },
  { title: "Les champignons de la France", author: "François Simon Cordier", year: "1870", language: "French", note: "A comprehensive 19th-c French field guide with hand-coloured plates.", pages: 684, illustrations: 60, importance: 76, rights: "Public domain", source: "Internet Archive", url: ia("leschampignonsde00cord"), image: cover("leschampignonsde00cord") },
  { title: "British Fungi (Hymenomycetes)", author: "John Stevenson", year: "1886", language: "English", note: "A major two-volume descriptive flora of British gilled and pored fungi.", pages: 420, illustrations: 5, importance: 70, rights: "Public domain", source: "Internet Archive", url: ia("hymenomycetesbri00stevrich"), image: cover("hymenomycetesbri00stevrich") },
  { title: "British Edible Fungi", author: "Mordecai Cubitt Cooke", year: "1891", language: "English", note: "A classic British popular edible-mushroom manual with colour plates.", pages: 310, illustrations: 12, importance: 64, rights: "Public domain", source: "Internet Archive", url: ia("britishediblefun00cook"), image: cover("britishediblefun00cook") },
  { title: "British Fungus-Flora", author: "George Massee", year: "1892–95", language: "English", note: "A four-volume classified text-book — a standard British reference flora.", pages: 456, illustrations: 40, importance: 68, rights: "Public domain", source: "Internet Archive", url: ia("britishfungusflo01mass"), image: cover("britishfungusflo01mass") },
  { title: "Mushrooms and Their Use", author: "Charles H. Peck", year: "1897", language: "English", note: "An accessible popular guide by New York's influential state botanist.", pages: 104, illustrations: 6, importance: 58, rights: "Public domain", source: "Internet Archive", url: ia("mushroomstheirus00peck"), image: cover("mushroomstheirus00peck") },
  { title: "Mycological Writings, Vol. 1", author: "Curtis Gates Lloyd", year: "1898–1905", language: "English", note: "Lloyd's eccentric, combative, encyclopedic privately-printed notes.", pages: 484, illustrations: 144, importance: 70, rights: "Public domain", source: "Internet Archive", url: ia("mycologicalwriti01lloy"), image: cover("mycologicalwriti01lloy") },
  { title: "Moulds, Mildews, and Mushrooms", author: "Lucien M. Underwood", year: "1899", language: "English", note: "An early American systematic teaching guide to fungi and Mycetozoa.", pages: 276, illustrations: 10, importance: 56, rights: "Public domain", source: "Internet Archive", url: ia("mouldsmildewsmus00unde"), image: cover("mouldsmildewsmus00unde") },
  { title: "Researches on Fungi", author: "A. H. Reginald Buller", year: "1909", language: "English", note: "A landmark scientific study of spore discharge and dispersal.", pages: 322, illustrations: 88, importance: 78, rights: "Public domain", source: "Internet Archive", url: ia("researchesonfung01bull"), image: cover("researchesonfung01bull") },
  { title: "A Monograph of the Mycetozoa", author: "Arthur & Gulielma Lister", year: "1911", language: "English", note: "The classic slime-mould monograph, with 78+ plates.", pages: 552, illustrations: 201, importance: 80, rights: "Public domain", source: "Internet Archive", url: ia("monographofmycet00brituoft"), image: cover("monographofmycet00brituoft") },
  { title: "Die Blätterpilze (Agaricaceae) Deutschlands", author: "Adalbert Ricken", year: "1915", language: "German", note: "The standard German agaric monograph, with plates.", pages: 646, illustrations: 112, importance: 66, rights: "Public domain", source: "Internet Archive", url: ia("dieblatterpilze0000adal"), image: cover("dieblatterpilze0000adal") },
  { title: "Mushrooms and Other Common Fungi", author: "Flora Patterson & Vera Charles", year: "1915", language: "English", note: "A practical USDA guide by two pioneering women mycologists.", pages: 110, illustrations: 30, importance: 62, rights: "Public domain", source: "Internet Archive", url: ia("mushroomsotherco175patt"), image: cover("mushroomsotherco175patt") },
  { title: "Edible and Poisonous Mushrooms", author: "William A. Murrill", year: "1916", language: "English", note: "A widely used American field handbook by the NYBG mycologist.", pages: 88, illustrations: 36, importance: 60, rights: "Public domain", source: "Internet Archive", url: ia("ediblepoisonous00murr"), image: cover("ediblepoisonous00murr") },
  { title: "The Agaricaceae of Michigan", author: "C. H. Kauffman", year: "1918", language: "English", note: "A landmark regional flora — a standard North American agaric monograph.", pages: 970, illustrations: 172, importance: 78, rights: "Public domain", source: "Internet Archive", url: ia("agaricaceaeofmic01kauf"), image: cover("agaricaceaeofmic01kauf") },
  { title: "Common Mushrooms of the United States", author: "L. C. C. Krieger", year: "1920", language: "English", note: "A USDA-illustrated popular national guide by a noted mushroom illustrator.", pages: 66, illustrations: 16, importance: 70, rights: "Public domain", source: "Internet Archive", url: ia("commonmushroomso00krieuoft"), image: cover("commonmushroomso00krieuoft") },
  { title: "The Romance of the Fungus World", author: "R. T. & F. W. Rolfe", year: "1925", language: "English", note: "A popular cultural and folklore account of fungi by BMS members.", pages: 376, illustrations: 85, importance: 55, rights: "Public domain", source: "Internet Archive", url: ia("romanceoffungusw00rolf"), image: cover("romanceoffungusw00rolf") },
];

export type FungiPlate = { src: string; caption: string; link: string };

export const FUNGI_PLATES: FungiPlate[] = [
  { src: "/fungi-source/plates/schaeffer-muscaria.jpg", caption: "Schäffer · Fly agaric (Amanita muscaria), 1762–74", link: "https://commons.wikimedia.org/wiki/File:Tab27-Agaricus_muscarius.jpg" },
  { src: "/fungi-source/plates/hussey-clathrus.jpg", caption: "Hussey · Latticed stinkhorn (Clathrus ruber), 1847", link: "https://commons.wikimedia.org/wiki/File:1847_Clathrus_ruber.jpg" },
  { src: "/fungi-source/plates/krombholz-7.jpg", caption: "Krombholz · Boletus regius, Tafel 7, 1831–46", link: "https://commons.wikimedia.org/wiki/File:Krombholz_mykologische_Hefte_Taf._7.jpg" },
  { src: "/fungi-source/plates/sowerby-1.jpg", caption: "Sowerby · Straw mushroom, Tab. 1, 1797", link: "https://commons.wikimedia.org/wiki/File:Coloured_Figures_of_English_Fungi_or_Mushrooms_-_t._1.jpg" },
  { src: "/fungi-source/plates/hussey-coccinea.jpg", caption: "Hussey · Scarlet waxcap (Hygrocybe coccinea), 1847", link: "https://commons.wikimedia.org/wiki/File:1847_Hygrocybe_coccinea.jpg" },
  { src: "/fungi-source/plates/schaeffer-deliciosus.jpg", caption: "Schäffer · Saffron milkcap (Lactarius deliciosus), 1762–74", link: "https://commons.wikimedia.org/wiki/File:Tab11-Agaricus_deliciosus.jpg" },
  { src: "/fungi-source/plates/bulliard-palmatus.jpg", caption: "Bulliard · Rhodotus palmatus, plate 216, 1785", link: "https://commons.wikimedia.org/wiki/File:Bulliard_-_Agaricus_palmatus.png" },
  { src: "/fungi-source/plates/cooke-749.jpg", caption: "Cooke · Cortinarius cotoneus, Pl. 749, 1888", link: "https://commons.wikimedia.org/wiki/File:Cooke-Illustrations_of_British_Fungi-Pl.749.jpg" },
  { src: "/fungi-source/plates/krombholz-37.jpg", caption: "Krombholz · Schwämme, Tafel 37, 1831–46", link: "https://commons.wikimedia.org/wiki/File:Krombholz_mykologische_Hefte_Taf._37.jpg" },
  { src: "/fungi-source/plates/schaeffer-campestris.jpg", caption: "Schäffer · Meadow mushroom (Agaricus campestris), 1762–74", link: "https://commons.wikimedia.org/wiki/File:Tab33-Agaricus_campestris_L.jpg" },
  { src: "/fungi-source/plates/bulliard-sanguineus.jpg", caption: "Bulliard · Russula sanguinea, 1781", link: "https://commons.wikimedia.org/wiki/File:Bulliard_-_Agaricus_sanguineus.png" },
  { src: "/fungi-source/plates/barla-agaricus.jpg", caption: "Barla · Les champignons de la province de Nice, 1859", link: "https://commons.wikimedia.org/wiki/File:BarlaLesChampignonsNiceAgaricus.jpg" },
  { src: "/fungi-source/plates/boudier-fistulina-hepatica.jpg", caption: "Boudier · Beefsteak fungus (Fistulina hepatica), 1905", link: "https://commons.wikimedia.org/wiki/File:Icones_mycologic%C3%A6,_ou_Iconographie_des_champignons_de_France_principalement_Discomycetes_(Pl._164)_(9801338214).jpg" },
  { src: "/fungi-source/plates/boudier-boletus-junquilleus.jpg", caption: "Boudier · Boletus junquilleus, 1905", link: "https://commons.wikimedia.org/wiki/File:Icones_mycologic%C3%A6,_ou_Iconographie_des_champignons_de_France_principalement_Discomycetes_(Pl._148)_(9801269175).jpg" },
  { src: "/fungi-source/plates/boudier-cortinarius-fulgens.jpg", caption: "Boudier · Cortinarius fulgens, 1905", link: "https://commons.wikimedia.org/wiki/File:Icones_mycologic%C3%A6,_ou_Iconographie_des_champignons_de_France_principalement_Discomycetes_(Pl._106)_(9801031115).jpg" },
  { src: "/fungi-source/plates/boudier-lactarius-rufus.jpg", caption: "Boudier · Lactarius rufus, 1905", link: "https://commons.wikimedia.org/wiki/File:Icones_mycologic%C3%A6,_ou_Iconographie_des_champignons_de_France_principalement_Discomycetes_(Pl._52)_(9800928224).jpg" },
  { src: "/fungi-source/plates/boudier-trametes-pini.jpg", caption: "Boudier · Trametes pini, 1905", link: "https://commons.wikimedia.org/wiki/File:Icones_mycologic%C3%A6,_ou_Iconographie_des_champignons_de_France_principalement_Discomycetes_(Pl._161)_(9801336926).jpg" },
  { src: "/fungi-source/plates/boudier-morchella-eximia.jpg", caption: "Boudier · Morchella eximia, 1905", link: "https://commons.wikimedia.org/wiki/File:Boudier_-_Morchella_eximia.png" },
  { src: "/fungi-source/plates/cooke-russula-emetica.jpg", caption: "Cooke · The sickener (Russula emetica), 1880s", link: "https://commons.wikimedia.org/wiki/File:Russula_emetica-Cooke.jpg" },
  { src: "/fungi-source/plates/cooke-russula-aurata.jpg", caption: "Cooke · Russula aurata, 1880s", link: "https://commons.wikimedia.org/wiki/File:Russula_aurata-Cooke.jpg" },
  { src: "/fungi-source/plates/cooke-russula-virescens.jpg", caption: "Cooke · Green-cracking russula (Russula virescens), 1880s", link: "https://commons.wikimedia.org/wiki/File:Russula_virescens-Cooke.jpg" },
  { src: "/fungi-source/plates/cooke-lactarius-deliciosus.jpg", caption: "Cooke · Saffron milkcap (Lactarius deliciosus), 1880s", link: "https://commons.wikimedia.org/wiki/File:Lactarius_deliciosus-Cooke.jpg" },
  { src: "/fungi-source/plates/cooke-cortinarius-triumphans.jpg", caption: "Cooke · Cortinarius triumphans, 1880s", link: "https://commons.wikimedia.org/wiki/File:Cooke_-_Cortinarius_triumphans.png" },
  { src: "/fungi-source/plates/sowerby-cantharellus-cibarius.jpg", caption: "Sowerby · Chanterelle (Cantharellus cibarius), 1797", link: "https://commons.wikimedia.org/wiki/File:Coloured_Figures_of_English_Fungi_or_Mushrooms_-_t._46.jpg" },
  { src: "/fungi-source/plates/sowerby-morchella-esculenta.jpg", caption: "Sowerby · Morel (Morchella esculenta), 1797", link: "https://commons.wikimedia.org/wiki/File:Coloured_Figures_of_English_Fungi_or_Mushrooms_-_t._51.jpg" },
  { src: "/fungi-source/plates/sowerby-hygrocybe-psittacina.jpg", caption: "Sowerby · Parrot waxcap (Hygrocybe psittacina), 1797", link: "https://commons.wikimedia.org/wiki/File:Coloured_Figures_of_English_Fungi_or_Mushrooms_-_t._82.jpg" },
  { src: "/fungi-source/plates/sowerby-boletus-edulis.jpg", caption: "Sowerby · Cep (Boletus edulis), 1797", link: "https://commons.wikimedia.org/wiki/File:Coloured_Figures_of_English_Fungi_or_Mushrooms_-_t._111.jpg" },
  { src: "/fungi-source/plates/sowerby-cortinarius-sanguineus.jpg", caption: "Sowerby · Bloodred webcap (Cortinarius sanguineus), 1797", link: "https://commons.wikimedia.org/wiki/File:Coloured_Figures_of_English_Fungi_or_Mushrooms_-_t._43.jpg" },
  { src: "/fungi-source/plates/krombholz-gyromitra-fastigiata.jpg", caption: "Krombholz · Gyromitra fastigiata, 1834", link: "https://commons.wikimedia.org/wiki/File:Krombholz_-_Helvella_fastigiata.png" },
  { src: "/fungi-source/plates/schaeffer-cantharellus-cibarius.jpg", caption: "Schäffer · Chanterelle (Cantharellus cibarius), 1762–74", link: "https://commons.wikimedia.org/wiki/File:Tab82-Agaricus_chantarellus_Schaeff.jpg" },
  { src: "/fungi-source/plates/schaeffer-russula-emetica.jpg", caption: "Schäffer · The sickener (Russula emetica), 1762–74", link: "https://commons.wikimedia.org/wiki/File:Tab15-Agaricus_emeticus.jpg" },
  { src: "/fungi-source/plates/schaeffer-lactarius-rufus.jpg", caption: "Schäffer · Rufous milkcap (Lactarius rufus), 1762–74", link: "https://commons.wikimedia.org/wiki/File:Tab73-Lactarius_rufus_Schaeff.jpg" },
  { src: "/fungi-source/plates/schaeffer-cortinarius-croceus.jpg", caption: "Schäffer · Cortinarius croceus, 1762–74", link: "https://commons.wikimedia.org/wiki/File:Tab4-Agaricus_croceus_Schaeff.jpg" },
  { src: "/fungi-source/plates/bulliard-boletus-aereus.jpg", caption: "Bulliard · Dark cep (Boletus aereus), 1789", link: "https://commons.wikimedia.org/wiki/File:Boletus_aereus_in_Bulliard_1789.jpg" },
  { src: "/fungi-source/plates/bulliard-amanita-ovoidea.jpg", caption: "Bulliard · Amanita ovoidea, 1790", link: "https://commons.wikimedia.org/wiki/File:Amanita_ovoidea_Bull.png" },
  { src: "/fungi-source/plates/bulliard-clavariadelphus-pistillaris.jpg", caption: "Bulliard · Giant club (Clavariadelphus pistillaris), 1784", link: "https://commons.wikimedia.org/wiki/File:Pierre_Bulliard;_Herbier_de_la_France;_Pl._244.jpg" },
  { src: "/fungi-source/plates/hussey-amanita-muscaria.jpg", caption: "Hussey · Fly agaric (Amanita muscaria), 1847", link: "https://commons.wikimedia.org/wiki/File:Illustrations_of_British_mycology_(Plate_I)_(8619405980).jpg" },
  { src: "/fungi-source/plates/hussey-boletus-luridus.jpg", caption: "Hussey · Lurid bolete (Boletus luridus), 1847", link: "https://commons.wikimedia.org/wiki/File:Illustrations_of_British_mycology_(Plate_VII)_(8619408150).jpg" },
  { src: "/fungi-source/plates/hussey-cortinarius-violaceus.jpg", caption: "Hussey · Violet webcap (Cortinarius violaceus), 1847", link: "https://commons.wikimedia.org/wiki/File:Illustrations_of_British_mycology_(Plate_XII)_(8619409866).jpg" },
  { src: "/fungi-source/plates/hussey-laetiporus-sulphureus.jpg", caption: "Hussey · Chicken of the woods (Laetiporus sulphureus), 1847", link: "https://commons.wikimedia.org/wiki/File:Illustrations_of_British_mycology_(Plate_XLVI)_(8619421228).jpg" },
  { src: "/fungi-source/plates/greville-leucocoprinus-cepistipes.jpg", caption: "Greville · Leucocoprinus cepistipes, 1823", link: "https://commons.wikimedia.org/wiki/File:Agaricus_cepaestipes_Greville.jpg" },
  { src: "/fungi-source/plates/bresadola-amanita-caesarea.jpg", caption: "Bresadola · Caesar's mushroom (Amanita caesarea), 1927", link: "https://commons.wikimedia.org/wiki/File:Bresadola_-_Amanita_caesarea.png" },
  { src: "/fungi-source/plates/bresadola-cantharellus-cibarius.jpg", caption: "Bresadola · Chanterelle (Cantharellus cibarius), 1927", link: "https://commons.wikimedia.org/wiki/File:Bresadola_-_Cantharellus_cibarius.png" },
  { src: "/fungi-source/plates/bresadola-hygrophorus-coccineus.jpg", caption: "Bresadola · Scarlet waxcap (Hygrophorus coccineus), 1927", link: "https://commons.wikimedia.org/wiki/File:Bresadola_-_Hygrophorus_coccineus.png" },
  { src: "/fungi-source/plates/bresadola-clavaria-aurea.jpg", caption: "Bresadola · Golden coral (Ramaria aurea), 1927", link: "https://commons.wikimedia.org/wiki/File:Bresadola-Clavaria_aurea_Schaeff.png" },
  { src: "/fungi-source/plates/bresadola-boletus-satanas.jpg", caption: "Bresadola · Devil's bolete (Boletus satanas), 1927", link: "https://commons.wikimedia.org/wiki/File:Bresadola-Boletus_Satanas.png" },
  { src: "/fungi-source/plates/bresadola-tremella-mesenterica.jpg", caption: "Bresadola · Witch's butter (Tremella mesenterica), 1927", link: "https://commons.wikimedia.org/wiki/File:Bresadola_-_Tremella_mesenterica.png" },
  { src: "/fungi-source/plates/bresadola-stropharia-aeruginosa.jpg", caption: "Bresadola · Verdigris roundhead (Stropharia aeruginosa), 1927", link: "https://commons.wikimedia.org/wiki/File:Bresadola_-_Stropharia_aeruginosa.png" },
];
