// The studio's points of view — a pool of one-line statements (biophilic design,
// patterns in nature, positive AI, systems thinking, what slime moulds and fungal
// networks can teach us). Shared by the closing CTA and the footer statement so
// both draw from the same voice.
export const BLURBS = [
  "We design the way nature does, with patterns, not blueprints.",
  "Everything is a system; we design the relationships, not just the parts.",
  "We study how things grow, then build things that grow well.",
  "Emergence over control: set the conditions and let the work find its form.",
  "Decentralised, adaptive, patient: the qualities we borrow from living systems.",
  "We'd rather grow a project like a garden than assemble it like a machine.",
  "A slime mould has no brain and still finds the shortest path. So can a product.",
  "An ecosystem balances many needs at once; so should the things we build.",
  "Resilience comes from diversity, in a forest and in a system alike.",
  "Murmurations have no leader and perfect coordination: a lesson for teams and tools.",
  "An interface should breathe with the user, not hold its breath waiting for input.",
  "We build for repair, because everything living gets repaired.",
  "Nature has been designing far longer than we have. We take notes.",
  "We treat the natural world as something the work answers to.",
  "Good design, like good soil, is mostly invisible and holds everything up.",
  "We use AI to widen what people can make, never to replace the maker.",
  "We use AI where it frees a person to do their best work, and nowhere it does the work for them.",
  "Accessibility isn't added at the end; it's who we were designing for all along.",
  "Good design widens the door; we try never to narrow it.",
  "Fairness is a system property: you design for it or you design against it.",
  "Diversity isn't decoration; it's how an ecosystem, or a team, stays standing.",
  "A thing made for everyone is usually better for anyone.",
  "Make it kind, make it clear, make it last.",
  "Care is a design material, and we try to use plenty of it.",
  "We try to make things we'd be glad to leave behind.",
  "We design the space for creativity, not just the path through it.",
  "We design the margins too: room to grow is part of the work.",
  "Design is a quiet way to help with loud problems.",
  "The things we make should still make sense to whoever inherits them.",
];
