// The studio's points of view — a pool of one-line statements (biophilic design,
// patterns in nature, positive AI, systems thinking, what slime moulds and fungal
// networks can teach us). Shared by the closing CTA and the footer statement so
// both draw from the same voice.
export const BLURBS = [
  "We design the way nature does — with patterns, not blueprints.",
  "Biophilic by default: software that brings a little more life into the room.",
  "The same spirals shape galaxies, ferns and an interface worth using.",
  "We use AI to widen what people can make — never to replace the maker.",
  "Everything is a system; we design the relationships, not just the parts.",
  "A slime mould has no brain and still finds the shortest path. So can a product.",
  "Fungal networks route nutrients to where they're needed. Good software routes attention.",
  "Simple rules, repeated, become complex life — and the best digital things.",
  "We'd rather grow a project like a garden than assemble it like a machine.",
  "Resilience is a forest trait: many small parts, quietly connected.",
  "Emergence over control — set the conditions and let the work find its form.",
  "Nature wastes nothing; neither should an interface.",
  "We study how things grow, then build things that grow well.",
  "Positive technology: tools that leave their users calmer than they found them.",
  "Mycelium thinks with its whole body. We try to design that way too.",
  "Feedback loops, not features, decide whether a system stays alive.",
  "The most advanced pattern is usually the oldest one in the field.",
  "Decentralised, adaptive, patient — the qualities we borrow from living systems.",
  "Good design, like good soil, is mostly invisible and holds everything up.",
  "We make for the long season — things that age into the landscape, not out of it.",
  "Design is how good intentions about the climate become things people actually use.",
  "We'd rather build tools that lighten a footprint than ones that grow it.",
  "A forest stores carbon quietly for centuries; we try to make things that last that patiently.",
  "Well-made and long-lived is a climate strategy, not just a craft one.",
  "Good design widens the door; we try never to narrow it.",
  "Who a thing is built for is a design decision — so we make it on purpose.",
  "Accessibility isn't added at the end; it's who we were designing for all along.",
  "Fairness is a system property: you design for it or you design against it.",
  "We share the planet with more minds than our own, and design can remember that.",
  "The best work leaves room for the more-than-human world.",
  "We design as if the landscape were a stakeholder, because it is.",
  "Leave it better than you found it — a coastline, a community, a codebase.",
  "Nature is the oldest design studio; mostly we just pay attention.",
  "We build tools that hand the pen back to the person holding it.",
  "The point of a good tool is the work it lets someone else make.",
  "Creativity needs room to wander, so we design the room, not the route.",
  "We'd rather lower the barrier to making than raise the ceiling on showing off.",
  "We use AI to remove the busywork, not the craft.",
  "AI should hand back time and let people spend it on the work that matters.",
  "An honest tool tells you what it's doing, then gets out of the way.",
  "Watch how a river finds its path and you've learned something about a hard problem.",
  "An ecosystem balances many needs at once; so should the things we build.",
  "Nature rarely optimises for one thing, and good design rarely should either.",
  "A leaf, a shell, a hive — each has something to teach an interface.",
  "The patterns that keep a wetland healthy can keep a product healthy too.",
  "Resilience comes from diversity, in a forest and in a system alike.",
  "Slow growth makes strong wood, and steadier work.",
  "Design is a quiet way to help with loud problems.",
  "Most big problems are design problems waiting for a patient hand.",
  "We'd like our work to be useful to the planet, not only to the brief.",
  "Care is a design material, and we try to use plenty of it.",
  "Doing less harm is the low bar; we'd rather design toward doing some good.",
  "We try to make things we'd be glad to leave behind.",
  "A wetland filters water by taking its time; the best systems do too.",
  "We prototype like seeds: cheap, many, and willing to fail toward the light.",
  "Murmurations have no leader and perfect coordination — a lesson for teams and tools.",
  "Bark, scale and feather all solve the same problem differently; so can a design.",
  "An interface should breathe with the user, not hold its breath waiting for input.",
  "Compounding beats cleverness — small good decisions daily, like rings in a tree.",
  "A coral reef is mostly cooperation; software can be too.",
  "We measure success in seasons, not sprints.",
  "Honest defaults are a form of respect.",
  "Tools should fit the hand and the habit, not the demo.",
  "Lichen is two lives doing better together; partnership is a design pattern.",
  "We design for the second use, and the hundredth, not just the first.",
  "Attention is the scarcest soil; we try not to strip-mine it.",
  "Roots talk before leaves do — the quiet layer is where the real work happens.",
  "A good system fails softly, like a branch that bends before it breaks.",
  "We'd rather be legible than impressive.",
  "Diversity isn't decoration; it's how an ecosystem — or a team — stays standing.",
  "The river doesn't rush the bend; neither should the roadmap.",
  "We build for repair, because everything living gets repaired.",
  "Light touch, deep roots.",
  "AI is a better shovel, not a replacement gardener.",
  "We try to make the right thing the easy thing.",
  "Patterns scale; pixels don't.",
  "Every default is an ethic wearing work clothes.",
  "Seed banks and source control share a goal: don't lose what's worth keeping.",
  "We design the margins too — room to grow is part of the work.",
  "A hive decides together and rarely regrets it; consensus can be quick.",
  "Weeds are plants thriving where we didn't plan; sometimes the bug is the feature.",
  "We aim for tools that make people feel more capable, not more watched.",
  "Pruning is growth; what we remove shapes a product as much as what we add.",
  "The forest floor recycles everything; good systems close their own loops.",
  "Make it kind, make it clear, make it last.",
];
