/**
 * Seeds the Frond Studio Sanity dataset with all 20 projects.
 * Run with:  SANITY_WRITE_TOKEN=xxx node scripts/seed.mjs
 * Media (video + poster) is read from /tmp/media_map.json (scraped from frond.studio).
 */
import { createClient } from "@sanity/client";
import { readFileSync } from "node:fs";

const token = process.env.SANITY_WRITE_TOKEN;
if (!token) throw new Error("Set SANITY_WRITE_TOKEN");

const client = createClient({
  projectId: "pzulxnho",
  dataset: "production",
  apiVersion: "2024-10-01",
  token,
  useCdn: false,
});

const media = JSON.parse(readFileSync("/tmp/media_map.json", "utf8"));

const decode = (s) =>
  (s || "")
    .replace(/&amp;/g, "&")
    .replace(/&#x27;/g, "'")
    .replace(/&#39;/g, "'")
    .replace(/&#8212;/g, "—")
    .replace(/&#8211;/g, "–")
    .replace(/&quot;/g, '"')
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">");

// Clean display title + tagline (from the projects index), plus scraped detail.
const DATA = [
  { slug: "ancient-wisdom-trust", title: "Ancient Wisdom Trust", subtitle: "New Website for Fundraising & Awareness", client: "Ancient Wisdom Trust", services: ["Website", "Design", "Development", "CMS", "Video"], liveUrl: "https://www.ancientwisdomtrust.org/", summary: "A visually rich, video-driven website with a scalable CMS that supports the Ancient Wisdom Trust's fundraising drive to digitise and translate inaccessible ancient texts.", overview: ["Created a new website to support fundraising efforts aimed at digitising and translating ancient texts that are currently inaccessible to both people and AI systems.", "Visually rich design with immersive video features. The aesthetic direction reflects the themes of lost and rediscovered knowledge.", "Scalable CMS collections for future expansion, with integrated links to a growing library of scanned and translated texts."] },
  { slug: "new-website-and-custom-graphics-for-all-things-fungi-festival", title: "All Things Fungi Festival", subtitle: "Supporting Festival Growth & Engagement", client: "All Things Fungi Festival", services: ["Website", "Design", "Development", "Creative", "CMS", "Forms", "Video"], liveUrl: "https://allthingsfungi.co.uk", summary: "A bold, interactive festival website with custom graphics, automated registration, and live iNaturalist data mapping that drew 10,000 views during the festival month.", overview: ["We created a dynamic website for the All Things Fungi Festival, celebrating the intersection of art, science, and groundbreaking fungal innovation. The site makes it easy for attendees to explore the festival while supporting organizers with smart digital tools.", "A full website redesign with bold visuals and a modern layout, including an interactive festival lineup, timetable and map, and a streamlined CMS for fast content updates.", "Automated forms and registration workflows, Mailchimp integration for newsletters and audience engagement, and a Mapbox visualization of iNaturalist data collected at the festival.", "10,000 website views during the festival month."] },
  { slug: "minor-am-website-development", title: "Minor AM", subtitle: "Custom Creative Website Development", client: "Minor AM", services: ["Website", "Development", "Design", "Animation", "CMS"], liveUrl: "https://minor-am.com", summary: "A custom, animation-rich website built from Figma for DJ and producer management agency Minor AM as part of a wider brand revamp.", overview: ["We partnered with Minor AM, an artist management company representing DJs and producers, to bring their new brand vision to life online. Using their Figma design as a foundation, we built a modern, dynamic website that elevates their digital presence and supports their artists.", "Custom development based on the Figma design, with creative layouts, sliders, and animations reflecting the brand's energy.", "A smooth CMS setup enabling easy content updates, with improved functionality and performance for a seamless user experience — part of a wider brand revamp to advance Minor AM's positioning."] },
  { slug: "give-and-go-sports-education-website", title: "Give and Go Sports Education", subtitle: "New Website & Documentary Rental Platform", client: "Give and Go Sports Education", services: ["Website", "Design", "Development", "Ecommerce", "Streaming", "CMS"], liveUrl: "https://giveandgosport.org", summary: "A new nonprofit website for Give & Go Sports Education featuring a custom documentary rental platform with ecommerce, streaming, and affiliate integration.", overview: ["We partnered with Give & Go Sports Education, a nonprofit advocating for multi-sport participation, to design and develop a new website that elevates their mission and brings their documentary directly to audiences.", "A documentary rental platform with custom ecommerce and streaming integration, an embedded trailer video to showcase the film, and a CMS-powered blog for articles and updates.", "An integrated affiliate system to expand reach and impact, plus a custom-designed About page highlighting their vision and values — a modern, engaging website that helped launch and distribute their documentary online."] },
  { slug: "timelapse-gallery", title: "Timelapse Media Production", subtitle: "Collection of Timelapse Media", client: null, services: ["Process Design", "Rigging", "Content Creation", "Consulting", "Video"], liveUrl: null, summary: "Frond's timelapse media production offering, covering process design, rigging, content creation, and consulting, with a focus on plants, fungi, and slime mold.", overview: ["We specialize in process design, rigging, content creation and consulting for timelapse photography and film production.", "Our passion is focussed on the kingdoms of plants, fungi and slime mold. We also offer a wealth of experience shooting timelapse of architecture, events and industrial applications. Feel free to contact us if you have any questions or upcoming timelapse projects."] },
  { slug: "logo-animation-gallery", title: "Logo Animations", subtitle: "Collection of Logo Animations", client: null, services: ["Logo Animation", "Motion Graphics", "Design", "Animation"], liveUrl: null, summary: "A gallery of custom logo animations and motion graphics built to make brands stand out across social media, websites, presentations and digital signage.", overview: ["Custom logo animations bring brand identities to life and create lasting impressions on audiences. We transform logos through a range of techniques including metallic reveals, glitch effects, chrome treatments, light rays, 3D elements and seamless looping designs.", "These animations are perfect for digital signage, social media, websites, presentations and video introductions, and work across diverse industries from technology to construction and environmental services.", "Featured work includes animations for clients such as CNC TECH, Symcyto, FeedbackFM, Hub, AM Logo, Lester Group Construction, Goodreau Tree Care and CCS."] },
  { slug: "moco-motion-control", title: "Mega Micro Motion Control", subtitle: "Advanced timelapse solutions", client: null, services: ["Video", "Timelapse", "Motion Control", "Creative"], liveUrl: null, summary: "A custom-built automated rail motion control system that brings cinema-class movement to macro and microscopic timelapse footage.", overview: ["Advanced timelapse solutions built around a customised automated rail motion system. The rig uses a high precision stepper motor with a custom Arduino controller, capable of producing thousands of frames per centimetre through incremental movements.", "The equipment was fabricated from reclaimed and found materials (except for key electronics) and can lift 15kg vertically, letting us add cinema-class motion control to macro and microscopic timelapse footage.", "A secondary prototype explores heliotropism, the phenomenon where plants track the sun's movement, using a full spectrum LED grow light that moves side to side to simulate solar movement while capturing plant timelapse footage."] },
  { slug: "whats-hot-lagos", title: "What's Hot Lagos", subtitle: "Beautiful Website & Local Business Directory", client: "What's Hot Lagos", services: ["Website", "Design", "Development", "CMS", "Video"], liveUrl: null, summary: "A beautiful, scalable destination guide and local business directory for Lagos, Portugal, complete with video and drone cinematography.", overview: ["What's Hot Lagos is a destination guide for discovering the best dining, accommodation and attractions in Lagos, Portugal. The client needed a website that combined aesthetic appeal with technical scalability and easy, user-friendly management.", "We delivered a beautiful and engaging visual design alongside infrastructure built for growth. The platform lets staff easily create, edit and manage template pages, collections and tags without technical barriers.", "Production incorporated extensive video content and drone cinematography to enhance the user experience and showcase the destination's appeal."] },
  { slug: "thomas-custom-marine", title: "Thomas Custom Marine", subtitle: "New Website & Custom Graphics", client: "Thomas Custom Marine", services: ["Website", "Design", "Development", "CMS", "Video"], liveUrl: "https://thomascustommarine.com", summary: "A sleek, modern Webflow website for Ontario's certified SeaDek fabricator, featuring custom video, cinemagraphs and a Google Maps powered business locator.", overview: ["We created a contemporary web presence for Thomas Custom Marine, an Ontario-based marine fabrication business and Certified SeaDek Fabricator.", "Design elements were crafted to differentiate the client from competitors, supported by custom video production and cinemagraph assets.", "A specialised integration combines Google Maps with Webflow's CMS to power a business locator tool, and the site also incorporates an online product catalogue for browsing their offerings."] },
  { slug: "danger-hockey-website", title: "Danger Hockey Development", subtitle: "Ecommerce Website Design & Development", client: "Danger Hockey Development", services: ["Website", "Design", "Development", "Ecommerce", "CMS", "Forms", "Video"], liveUrl: "https://www.dangerhockey.ca/", summary: "An action-packed, ecommerce-ready Webflow site for Canada's top hockey training program, with Shopify integration, custom video and logo animations.", overview: ["Danger Hockey Development runs Canada's top training programs for future hockey stars. They needed a website to showcase their commitment to excellence and facilitate their growth.", "We created an awesome, action-packed and professional site that enables the business to expand rapidly. It features seamless Shopify ecommerce integration with Webflow, is designed to stand out from the competition, and is built to scale way up.", "The site is action-packed with custom-made videos and logo animations, and DHD can easily create and edit new pages and products."] },
  { slug: "major-oem-manufacturer", title: "Major OEM Manufacturer", subtitle: "New Multilingual & Accessible Website", client: "Colonial Tool", services: ["Website", "Design", "Development", "CMS", "Forms", "Video"], liveUrl: "https://www.colonialtool.com/", summary: "A complete redesign of a major OEM manufacturer's website with new architecture, WCAG AA accessibility, multilingual translation, video assets, and an online product catalogue.", overview: ["We delivered a complete website redesign for a major OEM manufacturer, focusing on usability, accessibility, and multilingual support. The site features modern architecture, improved navigation, and enhanced multimedia content.", "Highlights include a full website redesign and new architecture for improved usability, WCAG AA accessibility compliance, and multilingual translation capabilities.", "New video assets and media integration, enhanced forms and interactive elements, an online product catalogue, and a mega navigation menu for streamlined access."] },
  { slug: "cunninghamsheetmetal-website-drone-videos-animated-timeline", title: "Cunningham Sheet Metal", subtitle: "New Website", client: "Cunningham Sheet Metal", services: ["Website", "Design", "Development", "Video"], liveUrl: "https://www.cunninghamsheetmetal.com/", summary: "A high-impact redesigned Webflow website for Cunningham Sheet Metal featuring drone photography, restored archival media, and HD fullscreen video.", overview: ["HD fullscreen video enriches the storytelling of quality craftsmanship backed by 100+ years of metalworking knowledge and innovation.", "From drone photography of their facility and restoring/digitizing archival media to a complete redesign and Webflow development of a high impact, responsive and dynamic website. Cunningham's new web presence stands out and communicates industry leadership."] },
  { slug: "thebracingexperts-website", title: "The Bracing Experts", subtitle: "Website Migration & Redesign", client: "The Bracing Experts", services: ["Website", "Design", "Development", "CMS"], liveUrl: "https://www.thebracingexperts.com/", summary: "A full website migration and redesign for The Bracing Experts, moving 80+ pages with new CMS collections, dynamic filtering, video parallax banners, multi-step forms, and major performance gains.", overview: ["Website migration and all-round enhancement, with a new design to reflect and accommodate the growth of the company.", "The project included migrating 80+ pages, 3 CMS collections, dynamic CMS filter and tagging, video parallax banners, automated email filtering and forwarding, complex multi-step form flows and internal company forms, and significantly improved site performance and health score."] },
  { slug: "goodreautreecare-website-drone-videos-logo-graphics", title: "Goodreau Tree Care", subtitle: "New Website & Custom Graphics", client: "Goodreau Tree Care", services: ["Website", "Design", "Development", "Video", "Branding"], liveUrl: "https://www.goodreautreecare.com/", summary: "A new website for Goodreau Tree Care paired with custom-made drone videos and animated video logo graphics.", overview: ["New and improved website complete with our custom-made drone videos and video logo graphics.", "Aerial drone cinematography and animated logo graphics give Goodreau Tree Care a distinctive, professional presence that stands apart from competitors."] },
  { slug: "symcyto-art-website-content", title: "SYMCYTO", subtitle: "Collaborative Art with Slime Mould", client: "Physarum polycephalum", services: ["Bio-art", "Content Production", "Timelapse", "Cultivation", "Installation"], liveUrl: null, summary: "A bio-art and timelapse documentary project created in collaboration with the slime mold Physarum polycephalum, exploring organic intelligence through cultivated, smart-enabled grow chambers and sculptural installations.", overview: ["Just as AI is creeping into our lives, nature poetically accelerates the endorsement of a lesser known form of intelligence. As if to remind the world that hidden amongst ancient organisms is an organic intelligence (an OI) that demonstrates the power of evolutionary programming. This is slime mold — a left field, decentralised, single-celled, pulsating problem solver.", "Not actually mold, but a collection of single celled organisms closely related to the amoeba family. These organisms possess advanced capabilities and intelligence demonstrated by their spatial awareness and problem solving skills. Several advanced algorithms have been developed based on numerous behavioral anomalies exhibited by this humble species.", "To honour and help increase the awareness of this organism we have been collaborating with the flagship species, Physarum polycephalum. United we have created a new form of harvest — a creative content branch that represents a fresh type of meta-fruiting body in the form of timelapse bio-art and documentary content.", "Our process involves cultivation of healthy, informed batches of slime mold which are introduced into smart-enabled mini studio ecosystems along with complimentary objects, ranging from simple agar panels and natural environment sets to novel items found in nature or sculpted in-house."] },
  { slug: "corporate-event-design-tenerife", title: "Spindrift", subtitle: "Event Design", client: "Spindrift", services: ["Event Design", "Video", "Creative"], liveUrl: null, summary: "A multi-day corporate getaway in Tenerife for 100+ guests, featuring workshops, a drone-cinematography crew, a Land Rover convoy to Mount Teide, and evening dinners and dance parties.", overview: ["The weekend kicked off at the legendary Auditorio de Tenerife designed by Santiago Calatrava — cocktails, dinner and a dance party. This set the tone for a highly collaborative and motivational series of presentations and workshops.", "The first days' conference room activities were topped with a drone workshop given together with a local movie crew specialising in drone cinematography.", "Once everyone's brains and stomachs were well fed, we arranged for a surprise convoy of Land Rovers to take 100+ people on an epic journey up above the clouds for an intimate view of the volcano, Mount Teide, with the drone crew standing by to capture some amazing footage."] },
  { slug: "canon-europe-ecommerce", title: "Canon", subtitle: "Creative Direction for Canon Europe Ecommerce", client: "Canon Europe", services: ["Design", "Branding", "Website", "Creative", "Ecommerce"], liveUrl: null, summary: "Experience design and creative direction for Canon Europe's two-year digital transformation and ecommerce program, launched across 23 countries.", overview: ["Experience Design and Creative Direction for a digital transformation and ecommerce program which launched in 23 countries.", "We provided on-site creative and tactical leadership for numerous phases over a two year period — training and supporting UX and design teams, establishing roles and responsibilities, and defining and documenting design/UX standards and guidelines.", "We established key process patterns and production frameworks for business-as-usual, campaigns, promotions, continuous improvement and optimisation streams.", "Design system updates supported evolving Canon Store promotions capabilities, including a 'Promotions Hub' landing experience and a set of modular components for product listing and site-wide merchandising."] },
  { slug: "clusewatches-ux-visual-design-frameworks", title: "Cluse", subtitle: "UX & Visual Frameworks", client: "CLUSE", services: ["Website", "Design", "Creative", "Timelapse"], liveUrl: null, summary: "UX and visual design frameworks built with the CLUSE teams to accelerate brand growth, including design systems, reusable toolkits and modernized, pattern-based workflows.", overview: ["Working closely with the CLUSE creative and marketing teams, our mission was to design, develop and enhance UX and visual design frameworks that would complement the growth of the organisation, their expanding commerce platform capabilities, and the evolution of the CLUSE brand.", "Deliverables included creating and documenting design systems and guidelines, and creating re-usable templates and toolkits to accelerate and enhance team capabilities.", "We augmented processes to be more pattern and systems-based for better automation, and assessed and modernized workflows and internal standards."] },
  { slug: "motorcitymotion-new-website", title: "Motor City Motion", subtitle: "Fresh Website", client: "Motor City Motion", services: ["Design", "Development", "Video", "Website"], liveUrl: "https://motorcitymotion.com", summary: "A fresh, modern and secure website designed, built and hosted for Ontario's Motor City Motion in under 10 days, featuring a migration, an advanced video library and improved site performance.", overview: ["We helped Motor City Motion to design, build and host a fresh, modern and secure web presence. Backed by amazing video assets and graphics from the Action Trackchair HQ, we were able to deliver a finished product in less than 10 days.", "Key accomplishments included a website migration, an advanced video solution and video library, and a significantly improved site performance and health score."] },
  { slug: "biophilia-matters-design-and-creative-strategy", title: "Biophilia Matters", subtitle: "Creative Strategy & Design", client: "Biophilia Matters", services: ["Creative", "Website", "Development", "Timelapse", "Video"], liveUrl: "https://biophiliamatters.com", summary: "Design and creative strategy for Biophilia Matters, covering brand and business design, website development, a content design system, custom smart grow systems and bespoke timelapse production.", overview: ["Exploring plant and fungi based innovation and appreciation through design and creative strategy.", "Deliverables spanned brand and business design, website design and development, content creation and a design system, the design, fabrication and documentation of smart grow systems, and custom timelapse rigging and production."] },
];

const block = (text, i) => ({
  _type: "block",
  _key: `b${i}`,
  style: "normal",
  markDefs: [],
  children: [{ _type: "span", _key: `s${i}`, text: decode(text), marks: [] }],
});

const docs = DATA.map((d, idx) => {
  const m = media[d.slug] || {};
  return {
    _id: `project-${d.slug}`,
    _type: "project",
    title: decode(d.title),
    subtitle: decode(d.subtitle),
    slug: { _type: "slug", current: d.slug },
    order: idx + 1,
    client: d.client ? decode(d.client) : undefined,
    services: d.services,
    summary: decode(d.summary),
    liveUrl: d.liveUrl || undefined,
    thumbnailVideo: m.mp4 || undefined,
    thumbnailImage: m.img || undefined,
    overview: d.overview.map((p, i) => block(p, i)),
  };
});

const run = async () => {
  let tx = client.transaction();
  for (const doc of docs) tx = tx.createOrReplace(doc);
  const res = await tx.commit();
  console.log(`Seeded ${docs.length} projects. Transaction ${res.transactionId}`);
};

run().catch((e) => {
  console.error(e);
  process.exit(1);
});
